#!/usr/bin/env bash

filtering(){

	if [[ ! "$1" =~ ^(200|201|204|301|302|307|308|401|403)$ ]]; then 

		return 1
	else
		return 0
	fi
}

validation(){

	if [[ "$1" = true || "$3" = true ]]; then

		if [[ "$1" = true ]]; then

			if [[ ! "$2" =~ https?://[0-9]{1,3}(\.[0-9]{1,3}){3}:[0-9]+ ]]; then

				echo "wrong url! enter valid url"
				exit
			else

        			if [[ "$3" = true ]]; then

                			if [[ -f "$4" ]]; then

						Starting_point "$2" "$4" "$5"
					else
						echo "File not found"
						exit 1
					fi

        			else
                			echo "Wordlist not given"
                			exit 1
        			fi
			fi
		else
        		echo ""
        		exit 1
		fi
	else
		echo "Input Error! uses -u for url -w for wordlist"
		exit 1
	fi


}
Starting_point(){

	ok_status=0
	word_count=$(wc -w "$2" | awk '{print $1}')
	ok_endpoints=()

	echo "==================================================="
	echo "	Mini Gobuster"
	echo "	Target	:  $1"
	echo "	Words	:  $word_count"
	echo "	Date	:  $(date +"%Y-%m-%d %H:%m")"
	echo "===================================================="
	echo -e "\n"

	while read -r line
	do
		status=$(curl -sI "$1"/"$line"/ | awk ' NR==1 {print $2}')

		if [[ "$status" = 200 ]]; then

			echo "[+] $status → /$line"
			((ok_status++))
			ok_endpoints+=("/$line")

		elif [[ "$status" = 301 ]]; then

			echo "[+] $status → /$line"
			ok_endpoints+=("/$line")

		elif [[ "$status" = 403 ]]; then

			echo "[+] $status → /$line"
			ok_endpoints+=("/$line")

		elif [[ "$status" = 404 ]]; then

			printf "[-] %s → /%-20s %s\n" "$status" "$line" "(hidden, only shows with -v)"

		fi

	done < "$2"

	final_report $ok_status $word_count ok_endpoints
}
final_report(){

	local -n endpoint="$3"
	echo -e "\n"
	echo -e "====================================\n"
	echo -e "\n[FOUND ENDPOINTS]\n"
		for valid in "${endpoint[@]}"
		do
			echo "[+] $valid"
		done

	echo -e "\n====================================="
	echo -e "\n"
	echo "====================================="

	printf "[*] %-10s : %s\n" "Found" "$1"
	printf "[*] %-10s : %s\n" "Tested" "$2"

	echo "====================================="
}
while getopts ":u:w:c:" opts
do
	case "$opts" in
		u) url="$OPTARG"
		   u_give=true;;
		w) wordlist="$OPTARG"
		   w_give=true;;
		c) filter_status="$OPTARG"
		   c_give=true;;
	esac
done

if [[ "$c_give" = true ]]; then

	if [[ ! "$filter_status" =~ ^[0-9,]+$ ]]; then
		echo "Status filter or matcher -c: invalid value"
		exit 1 
	else 
		echo "$filter_status"
	fi
fi
validation "$u_give" "$url" "$w_give" "$wordlist" 


