#!/usr/bin/env bash

filtering(){

	

	if [[ ! "$1" =~ ^(200|201|204|301|302|307|308|401|403)$ ]]; then 

		return 1
	else
		return 0
	fi
}

validate_flag_u(){

	if [[ ! "$1" =~ http://127.0.0.1:9000 ]] && [[ ! "$1" =~ https?://(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z0-9]{2,} ]] ; then
		echo "Invalid Url! enter correct url"
		exit 1
	fi

	echo "$1"
}

validate_flag_w(){

	if [[ -f "$1" ]];  then

		echo "Error! File Not Exist"
		exit 1
	fi

	echo "$1"
}
validate_c(){

	if [[ "$1" == true ]]; then

		if [[ ! "$2" =~ ^[0-9,]+$ ]]; then

			echo "Error! wrong status code"
			exit 1
		fi
	else
		echo "./mini_Gobuster: option requires an argument -- c"
		exit 1
	fi

	echo "$2"
}

Starting_point(){

	ok_status=0
	word_count=$(wc -w "$2" | awk '{print $1}')
	ok_endpoints=()

	echo "==================================================="
	echo "	Mini Gobuster"
	echo "	Target	:  $1"
	echo "	Words	:  $word_count"
	echo "	Date	:  $(date +"%Y-%m-%d %H:%m")"
	echo "===================================================="
	echo -e "\n"

	while read -r line
	do
		status=$(curl -sI "$1"/"$line"/ | awk ' NR==1 {print $2}')

		if [[ "$status" = 200 ]]; then

			echo "[+] $status → /$line"
			((ok_status++))
			ok_endpoints+=("/$line")

		elif [[ "$status" = 301 ]]; then

			echo "[+] $status → /$line"
			ok_endpoints+=("/$line")

		elif [[ "$status" = 403 ]]; then

			echo "[+] $status → /$line"
			ok_endpoints+=("/$line")

		elif [[ "$status" = 404 ]]; then

			printf "[-] %s → /%-20s %s\n" "$status" "$line" "(hidden, only shows with -v)"

		fi

	done < "$2"

	final_report $ok_status $word_count ok_endpoints
}
final_report(){

	local -n endpoint="$3"
	echo -e "\n"
	echo -e "====================================\n"
	echo -e "\n[FOUND ENDPOINTS]\n"
		for valid in "${endpoint[@]}"
		do
			echo "[+] $valid"
		done

	echo -e "\n====================================="
	echo -e "\n"
	echo "====================================="

	printf "[*] %-10s : %s\n" "Found" "$1"
	printf "[*] %-10s : %s\n" "Tested" "$2"

	echo "====================================="
}
while getopts ":u:w:c:" opts
do
	case "$opts" in
		u) url="$OPTARG"
		   u_give=true;;
		w) wordlist="$OPTARG"
		   w_give=true;;
		c) filter_status="$OPTARG"
		   c_give=true;;
	esac
done

if [[ ! "$u_give" = true ]]; then

	echo "./mini_Gobuster: option requires an argument -- u"
	exit 1

fi
if [[ ! "$w_give" = true ]]; then

	echo "./mini_Gobuster: option requires an argument -- w"
	exit
fi

validate_flag_u "$url"
validate_flag_w "$wordlist"
validate_flag_c "$c_give" "$filter_status"
