#!/usr/bin/env bash

validation(){

	if [[ "$1" = true || "$3" = true ]]; then
		if [[ "$1" = true ]]; then

        		if [[ "$3" = true ]]; then

                		echo "Nothing"

        		else
                		echo "Wordlist not given"
                		exit 1
        		fi

		else
        		echo ""
        		exit 1
		fi
	else 
		echo "Input Error! uses -u for url -w for wordlist"
		exit 1
	fi


}

while getopts ":u:w:c:" opts
do
	case "$opts" in
		u) url="$OPTARG"
		   u_give=true;;
		w) wordlist="$OPTARG"
		   w_give=true;;
		c) filter_status="$OPTARG"
		   c_give=true;;
	esac
done

validation "$u_give" "$url" "$w_give" "$wordlist"
